In [1]:
# pip install -r ../requirements.txt

In [2]:
from utils import utils
from app import run_app, App

settings = utils.get_settings_notebook('../settings.json')
utils.pretty_print(settings)

=======
{
    "extract": {
        "cast": {
            "filepath_or_buffer": "files/archive/AllMoviesCastingRaw.csv",
            "sep": ";"
        },
        "directors": {
            "filepath_or_buffer": "files/archive/900_acclaimed_directors_awards.csv",
            "sep": ";"
        },
        "movies": {
            "filepath_or_buffer": "files/archive/AllMoviesDetailsCleaned.csv",
            "sep": ";"
        }
    },
    "load": {
        "constraints": [
            {
                "field": "name",
                "name": "Genres",
                "node_name": "Genre"
            },
            {
                "field": "name",
                "name": "People",
                "node_name": "Person"
            },
            {
                "field": "movie_id",
                "name": "Movies",
                "node_name": "Movie"
            }
        ],
        "data": {
            "genres": [
                {
                    "cols": [
                        "name"
                    ],
                    "node_name": "Genre",
                    "ref": "g"
                }
            ],
            "movies": [
                {
                    "cols": [
                        "movie_id",
                        "imdb_id",
                        "lang",
                        "title",
                        "overview"
                    ],
                    "node_name": "Movie",
                    "ref": "m"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Person",
                    "ref": "d",
                    "relations": [
                        {
                            "begins": "d",
                            "begins_dir": "-",
                            "ends": "m",
                            "ends_dir": "->",
                            "name": "DIRECTED"
                        }
                    ],
                    "unwind": "directors"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Genre",
                    "ref": "g",
                    "relations": [
                        {
                            "begins": "m",
                            "begins_dir": "-",
                            "ends": "g",
                            "ends_dir": "->",
                            "name": "HAS_GENRE"
                        }
                    ],
                    "unwind": "genres"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Person",
                    "ref": "a",
                    "relations": [
                        {
                            "begins": "a",
                            "begins_dir": "-",
                            "ends": "m",
                            "ends_dir": "->",
                            "name": "ACTED_IN"
                        }
                    ],
                    "unwind": "actors"
                }
            ],
            "people": [
                {
                    "cols": [
                        "name",
                        "gender"
                    ],
                    "node_name": "Person",
                    "ref": "p"
                }
            ]
        }
    },
    "neo4j": {
        "cap_insert": 25000,
        "clear_data": true,
        "db": null,
        "file_folder": "../import/",
        "insertion_mode": "rows",
        "password": "1234",
        "uri": "bolt://localhost:7687",
        "username": "neo4j"
    },
    "transform": {
        "cast": {
            "column_map": {
                "actor1_gender": "actor1_gender",
                "actor1_name": "actor1_name",
                "actor2_gender": "actor2_gender",
                "actor2_name": "actor2_name",
                "actor3_gender": "actor3_gender",
                "actor3_name": "actor3_name",
                "actor4_gender": "actor4_gender",
                "actor4_name": "actor4_name",
                "actor5_gender": "actor5_gender",
                "actor5_name": "actor5_name",
                "director_gender": "director_gender",
                "director_name": "director_name",
                "id": "movie_id"
            }
        },
        "directors": {
            "column_map": {
                "Academy Fellowship": "acad_fellow",
                "name": "name"
            }
        },
        "movies": {
            "column_map": {
                "genres": "genres",
                "id": "movie_id",
                "imdb_id": "imdb_id",
                "original_language": "lang",
                "original_title": "title",
                "overview": "overview"
            }
        }
    }
}
======

In [3]:
import pandas as pd
df = pd.read_csv(**settings['extract']['directors'])
df.head()

,name,tmdbID,imdbID,Total awards,Academy Fellowship,Academy Fellowship_won,Academy Fellowship_nominated,Gold Hugo,Gold Hugo_won,Gold Hugo_nominated,...,Orpheus Award_nominated,Arte France Cinéma Award,Arte France Cinéma Award_won,Arte France Cinéma Award_nominated,Citizens Award,Citizens Award_won,Citizens Award_nominated,Cowboy Award,Cowboy Award_won,Cowboy Award_nominated
0,Ingmar Bergman,6648,nm0000005,101,1,1,0,2,0,2,...,0,0,0,0,0,0,0,0,0,0
1,Marlon Brando,3084,nm0000008,58,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Federico Fellini,4415,nm0000019,90,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
3,Alfred Hitchcock,2636,nm0000033,53,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Buster Keaton,8635,nm0000036,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
data_df = run_app(settings, 'extract_transform')

==== TRANSFORM directors ====

/Users/leonardoclo/git/dse-203/src/core/core.py:8: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(**settings['extract'][k])

==== TRANSFORM movies ====
==== TRANSFORM cast ====

In [5]:
etl = run_app(settings, 'etl')

==== TRANSFORM directors ====

/Users/leonardoclo/git/dse-203/src/core/core.py:8: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(**settings['extract'][k])

==== TRANSFORM movies ====
==== TRANSFORM cast ====
CREATE CONSTRAINT Genres
        IF NOT EXISTS ON (c:Genre)
        ASSERT c.name IS UNIQUE
CREATE CONSTRAINT People
        IF NOT EXISTS ON (c:Person)
        ASSERT c.name IS UNIQUE
CREATE CONSTRAINT Movies
        IF NOT EXISTS ON (c:Movie)
        ASSERT c.movie_id IS UNIQUE
batch 0
UNWIND $rows AS row

MERGE (p:Person {name: row.name, gender: row.gender})

RETURN count(*) as total
batch 1
UNWIND $rows AS row

MERGE (p:Person {name: row.name, gender: row.gender})

RETURN count(*) as total
batch 2
UNWIND $rows AS row

MERGE (p:Person {name: row.name, gender: row.gender})

RETURN count(*) as total
batch 0
UNWIND $rows AS row

MERGE (g:Genre {name: row.name})

RETURN count(*) as total
batch 1
UNWIND $rows AS row

MERGE (g:Genre {name: row.name})

RETURN count(*) as total
batch 2
UNWIND $rows AS row

MERGE (g:Genre {name: row.name})

RETURN count(*) as total
batch 0
UNWIND $rows AS row

MERGE (m:Movie {movie_id: row.movie_id, imdb_id: row.imdb_id, lang: row.lang, title: row.title, overview: row.overview})

WITH row, m
UNWIND row.directors AS directors
MATCH (d:Person {name: directors.name})
MERGE (d)-[:DIRECTED]->(m)
WITH row, m
UNWIND row.genres AS genres
MATCH (g:Genre {name: genres.name})
MERGE (m)-[:HAS_GENRE]->(g)
WITH row, m
UNWIND row.actors AS actors
MATCH (a:Person {name: actors.name})
MERGE (a)-[:ACTED_IN]->(m)
RETURN count(*) as total
batch 1
UNWIND $rows AS row

MERGE (m:Movie {movie_id: row.movie_id, imdb_id: row.imdb_id, lang: row.lang, title: row.title, overview: row.overview})

WITH row, m
UNWIND row.directors AS directors
MATCH (d:Person {name: directors.name})
MERGE (d)-[:DIRECTED]->(m)
WITH row, m
UNWIND row.genres AS genres
MATCH (g:Genre {name: genres.name})
MERGE (m)-[:HAS_GENRE]->(g)
WITH row, m
UNWIND row.actors AS actors
MATCH (a:Person {name: actors.name})
MERGE (a)-[:ACTED_IN]->(m)
RETURN count(*) as total
batch 2
UNWIND $rows AS row

MERGE (m:Movie {movie_id: row.movie_id, imdb_id: row.imdb_id, lang: row.lang, title: row.title, overview: row.overview})

WITH row, m
UNWIND row.directors AS directors
MATCH (d:Person {name: directors.name})
MERGE (d)-[:DIRECTED]->(m)
WITH row, m
UNWIND row.genres AS genres
MATCH (g:Genre {name: genres.name})
MERGE (m)-[:HAS_GENRE]->(g)
WITH row, m
UNWIND row.actors AS actors
MATCH (a:Person {name: actors.name})
MERGE (a)-[:ACTED_IN]->(m)
RETURN count(*) as total

In [6]:
data_df

{'people':                     name  gender
 0         Aki Kaurismäki     0.0
 1        Matti Pellonpää     2.0
 4           Kati Outinen     1.0
 5       Sakari Kuosmanen     2.0
 6           Esko Nikkari     2.0
 ...                  ...     ...
 48151  Frederick Leister     2.0
 48184          Lee Moran     2.0
 48192              Ma Li     1.0
 48202      Rafael Campos     2.0
 48230    Melissa Gilbert     1.0

 [12354 rows x 2 columns],
 'genres':                  name
 0               Drama
 1               Crime
 3              Comedy
 4           Animation
 5              Family
 8             Romance
 10            Mystery
 14              Music
 15          Adventure
 16            Fantasy
 17             Action
 18           Thriller
 19    Science Fiction
 25                War
 28            Western
 89        Documentary
 176            Horror
 297           History
 485           Foreign
 2792         TV Movie,
 'movies':        movie_id    imdb_id lang                                   title  \
 0             2  tt0094675   fi                                   Ariel
 1             3  tt0092149   fi                    Varjoja paratiisissa
 2            12  tt0266543   en                            Finding Nemo
 3            13  tt0109830   en                            Forrest Gump
 4            14  tt0169547   en                         American Beauty
 ...         ...        ...  ...                                     ...
 11439    468134  tt0174108   en                             Paviljon VI
 11440    468188  tt0020291   en                               Prisoners
 11441    468335  tt0020128   en                     Madonna of Avenue A
 11442    468749  tt0083115   en                   Splendor in the Grass
 11443    468923  tt4607540   en  Back to the Future: Hilarious Outtakes

                                                 overview  \
 0      Taisto Kasurinen is a Finnish coal miner whose...
 1      An episode in the life of Nikander, a garbage ...
 2      Nemo, an adventurous young clownfish, is unexp...
 3      A man with a low IQ has accomplished great thi...
 4      Lester Burnham, a depressed suburban father in...
 ...                                                  ...
 11439  A doctor from provincial town in Tsardom of Ru...
 11440  Prisoners was a 1929 American film directed by...
 11441  Madonna of Avenue A is a 1929 talking drama fi...
 11442  Splendor in the Grass is a made-for-TV movie s...
 11443  A short blooper reel from the filming of the 1...

                                                   genres  \
 0                 [{'name': 'Drama'}, {'name': 'Crime'}]
 1                [{'name': 'Drama'}, {'name': 'Comedy'}]
 2            [{'name': 'Animation'}, {'name': 'Family'}]
 3      [{'name': 'Comedy'}, {'name': 'Drama'}, {'name...
 4                                    [{'name': 'Drama'}]
 ...                                                  ...
 11439                                [{'name': 'Drama'}]
 11440                                [{'name': 'Drama'}]
 11441                                [{'name': 'Drama'}]
 11442                                [{'name': 'Drama'}]
 11443                               [{'name': 'Comedy'}]

                                                   actors  \
 0      [{'name': 'Matti Pellonpää', 'gender': 2}, {'n...
 1      [{'name': 'Matti Pellonpää', 'gender': 2}, {'n...
 2      [{'name': 'Albert Brooks', 'gender': 2}, {'nam...
 3      [{'name': 'Tom Hanks', 'gender': 2}, {'name': ...
 4      [{'name': 'Kevin Spacey', 'gender': 2}, {'name...
 ...                                                  ...
 11439                                                 []
 11440  [{'name': 'Ian Keith', 'gender': 2}, {'name': ...
 11441  [{'name': 'Dolores Costello', 'gender': 1.0}, ...
 11442  [{'name': 'Michelle Pfeiffer', 'gender': 1.0},...
 11443  [{'name': 'Michael J. Fox', 'gender': 2.0}, {'...

                                               directors
 0           [{'name': 'Aki Kaurismäki', 'gender': 0.0}]
 1           [{'name': 'Aki Kaurismäki', 'gender': 0.0}]
 2           [{'name': 'Andrew Stanton', 'gender': 2.0}]
 3          [{'name': 'Robert Zemeckis', 'gender': 2.0}]
 4               [{'name': 'Sam Mendes', 'gender': 2.0}]
 ...                                                 ...
 11439      [{'name': 'Lucian Pintilie', 'gender': 2.0}]
 11440    [{'name': 'William A. Seiter', 'gender': 2.0}]
 11441       [{'name': 'Michael Curtiz', 'gender': 0.0}]
 11442  [{'name': 'Richard C. Sarafian', 'gender': 0.0}]
 11443      [{'name': 'Robert Zemeckis', 'gender': 2.0}]

 [11444 rows x 8 columns]}