In [1]:
import warnings
# warnings.filterwarnings("ignore",category=DeprecationWarning)
warnings.filterwarnings("ignore")
from utils import utils
from app import run_app, App
from core.gen_topics import gen_topics
import pandas as pd
import copy
settings = utils.get_settings_notebook('../settings.json')
utils.pretty_print(settings)

/opt/Anaconda/anaconda3/envs/ucsd1/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload

=======
{
    "extract": {
        "cast": {
            "filepath_or_buffer": "files/archive/AllMoviesCastingRaw.csv",
            "sep": ";"
        },
        "directors": {
            "filepath_or_buffer": "files/archive/900_acclaimed_directors_awards.csv",
            "sep": ";"
        },
        "movies": {
            "filepath_or_buffer": "files/archive/AllMoviesDetailsCleaned.csv",
            "sep": ";"
        }
    },
    "load": {
        "constraints": [
            {
                "field": "name",
                "name": "Companies",
                "node_name": "Company"
            },
            {
                "field": "name",
                "name": "Genres",
                "node_name": "Genre"
            },
            {
                "field": "name",
                "name": "People",
                "node_name": "Person"
            },
            {
                "field": "movie_id",
                "name": "Movies",
                "node_name": "Movie"
            }
        ],
        "data": {
            "company": [
                {
                    "cols": [
                        "name"
                    ],
                    "node_name": "Company",
                    "ref": "c"
                }
            ],
            "genres": [
                {
                    "cols": [
                        "name"
                    ],
                    "node_name": "Genre",
                    "ref": "g"
                }
            ],
            "movies": [
                {
                    "cols": [
                        "movie_id",
                        "imdb_id",
                        "lang",
                        "title",
                        "overview"
                    ],
                    "node_name": "Movie",
                    "ref": "m"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Person",
                    "ref": "d",
                    "relations": [
                        {
                            "begins": "d",
                            "begins_dir": "-",
                            "ends": "m",
                            "ends_dir": "->",
                            "name": "DIRECTED"
                        }
                    ],
                    "unwind": "directors"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Company",
                    "ref": "c",
                    "relations": [
                        {
                            "begins": "c",
                            "begins_dir": "-",
                            "ends": "m",
                            "ends_dir": "->",
                            "name": "PRODUCED"
                        }
                    ],
                    "unwind": "companies"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Genre",
                    "ref": "g",
                    "relations": [
                        {
                            "begins": "m",
                            "begins_dir": "-",
                            "ends": "g",
                            "ends_dir": "->",
                            "name": "HAS_GENRE"
                        }
                    ],
                    "unwind": "genres"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Person",
                    "ref": "a",
                    "relations": [
                        {
                            "begins": "a",
                            "begins_dir": "-",
                            "ends": "m",
                            "ends_dir": "->",
                            "name": "ACTED_IN"
                        }
                    ],
                    "unwind": "actors"
                }
            ],
            "people": [
                {
                    "cols": [
                        "name",
                        "gender"
                    ],
                    "node_name": "Person",
                    "ref": "p"
                }
            ]
        }
    },
    "neo4j": {
        "cap_insert": 25000,
        "clear_data": true,
        "db": null,
        "file_folder": "../import/",
        "insertion_mode": "rows",
        "password": "1234",
        "uri": "bolt://localhost:7687",
        "username": "neo4j"
    },
    "transform": {
        "cast": {
            "column_map": {
                "actor1_gender": "actor1_gender",
                "actor1_name": "actor1_name",
                "actor2_gender": "actor2_gender",
                "actor2_name": "actor2_name",
                "actor3_gender": "actor3_gender",
                "actor3_name": "actor3_name",
                "actor4_gender": "actor4_gender",
                "actor4_name": "actor4_name",
                "actor5_gender": "actor5_gender",
                "actor5_name": "actor5_name",
                "director_gender": "director_gender",
                "director_name": "director_name",
                "id": "movie_id"
            }
        },
        "directors": {
            "column_map": {
                "Academy Fellowship": "acad_fellow",
                "name": "name"
            }
        },
        "movies": {
            "column_map": {
                "genres": "genres",
                "id": "movie_id",
                "imdb_id": "imdb_id",
                "original_language": "lang",
                "original_title": "title",
                "overview": "overview",
                "production_companies": "company"
            }
        }
    }
}
======

In [2]:
data_df = run_app(settings, 'extract_transform')

==== TRANSFORM directors ====
==== TRANSFORM movies ====
==== TRANSFORM cast ====

In [3]:
data_df['movies'].shape

(11842, 9)

In [7]:
data_df['movies'][data_df['movies']['overview'].apply(lambda x: x is not None and len(x) > 30)]

,movie_id,imdb_id,lang,title,overview,genres,actors,directors,companies
0,2,tt0094675,fi,Ariel,Taisto Kasurinen is a Finnish coal miner whose...,"[{'name': 'Drama'}, {'name': 'Crime'}]","[{'name': 'Matti Pellonpää', 'gender': 2}, {'n...","[{'name': 'Aki Kaurismaki', 'gender': 0.0}]",[{'name': 'Villealfa Filmproduction Oy'}]
1,3,tt0092149,fi,Varjoja paratiisissa,"An episode in the life of Nikander, a garbage ...","[{'name': 'Drama'}, {'name': 'Comedy'}]","[{'name': 'Matti Pellonpää', 'gender': 2}, {'n...","[{'name': 'Aki Kaurismaki', 'gender': 0.0}]",[{'name': 'Villealfa Filmproduction Oy'}]
2,12,tt0266543,en,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...","[{'name': 'Animation'}, {'name': 'Family'}]","[{'name': 'Albert Brooks', 'gender': 2}, {'nam...","[{'name': 'Andrew Stanton', 'gender': 2.0}]",[{'name': 'Pixar Animation Studios'}]
3,13,tt0109830,en,Forrest Gump,A man with a low IQ has accomplished great thi...,"[{'name': 'Comedy'}, {'name': 'Drama'}, {'name...","[{'name': 'Tom Hanks', 'gender': 2}, {'name': ...","[{'name': 'Robert Zemeckis', 'gender': 2.0}]",[{'name': 'Paramount Pictures'}]
4,14,tt0169547,en,American Beauty,"Lester Burnham, a depressed suburban father in...",[{'name': 'Drama'}],"[{'name': 'Kevin Spacey', 'gender': 2}, {'name...","[{'name': 'Sam Mendes', 'gender': 2.0}]",[{'name': 'DreamWorks SKG'}]
...,...,...,...,...,...,...,...,...,...
11837,468134,tt0174108,en,Paviljon VI,A doctor from provincial town in Tsardom of Ru...,[{'name': 'Drama'}],[],"[{'name': 'Lucian Pintilie', 'gender': 2.0}]",[{'name': 'Centar Film'}]
11838,468188,tt0020291,en,Prisoners,Prisoners was a 1929 American film directed by...,[{'name': 'Drama'}],"[{'name': 'Ian Keith', 'gender': 2}, {'name': ...","[{'name': 'William A Seiter', 'gender': 2.0}]",[{'name': 'First National Pictures'}]
11839,468335,tt0020128,en,Madonna of Avenue A,Madonna of Avenue A is a 1929 talking drama fi...,[{'name': 'Drama'}],"[{'name': 'Dolores Costello', 'gender': 1.0}, ...","[{'name': 'Michael Curtiz', 'gender': 0.0}]",[{'name': 'Warner Bros.'}]
11840,468749,tt0083115,en,Splendor in the Grass,Splendor in the Grass is a made-for-TV movie s...,[{'name': 'Drama'}],"[{'name': 'Michelle Pfeiffer', 'gender': 1.0},...","[{'name': 'Richard C Sarafian', 'gender': 0.0}]",[{'name': 'none'}]
11841,468923,tt4607540,en,Back to the Future: Hilarious Outtakes,A short blooper reel from the filming of the 1...,[{'name': 'Comedy'}],"[{'name': 'Michael J. Fox', 'gender': 2.0}, {'...","[{'name': 'Robert Zemeckis', 'gender': 2.0}]",[{'name': 'Universal Pictures'}]

In [8]:
movie_topics = gen_topics()
# (df_movie_topics, df_topic_words) = movie_topics.batch_process(data_df['movies'][data_df['movies']['lang'] == 'en'])
(df_movie_topics, df_topic_words) = movie_topics.batch_process(data_df['movies'][data_df['movies']['overview'].apply(lambda x: x is not None and len(x) > 30)])

2022-12-08 21:37:46 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
2022-12-08 21:37:46,826 : INFO : Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.4.1.json: 193kB [00:00, 4.89MB/s]
2022-12-08 21:37:48 INFO: Loading these models for language: en (English):
============================
| Processor    | Package   |
----------------------------
| tokenize     | combined  |
| pos          | combined  |
| lemma        | combined  |
| depparse     | combined  |
| sentiment    | sstplus   |
| constituency | wsj       |
| ner          | ontonotes |
============================

2022-12-08 21:37:48,144 : INFO : Loading these models for language: en (English):
============================
| Processor    | Package   |
----------------------------
| tokenize     | combined  |
| pos          | combined  |
| lemma        | combined  |
| depparse     | combined  |
| sentiment    | sstplus   |
| constituency | wsj       |
| ner          | ontonotes |
============================

2022-12-08 21:37:48 INFO: Use device: gpu
2022-12-08 21:37:48,144 : INFO : Use device: gpu
2022-12-08 21:37:48 INFO: Loading: tokenize
2022-12-08 21:37:48,145 : INFO : Loading: tokenize
2022-12-08 21:37:48 INFO: Loading: pos
2022-12-08 21:37:48,157 : INFO : Loading: pos
2022-12-08 21:37:48 INFO: Loading: lemma
2022-12-08 21:37:48,358 : INFO : Loading: lemma
2022-12-08 21:37:48 INFO: Loading: depparse
2022-12-08 21:37:48,387 : INFO : Loading: depparse
2022-12-08 21:37:48 INFO: Loading: sentiment
2022-12-08 21:37:48,531 : INFO : Loading: sentiment
2022-12-08 21:37:48 INFO: Loading: constituency
2022-12-08 21:37:48,823 : INFO : Loading: constituency
2022-12-08 21:37:49 INFO: Loading: ner
2022-12-08 21:37:49,130 : INFO : Loading: ner
2022-12-08 21:37:49 INFO: Done loading processors!
2022-12-08 21:37:49,452 : INFO : Done loading processors!

In [9]:
display(df_topic_words)
display(df_movie_topics)

,0,1,2,3,4,5,6,7,8,9
0,"""bill""","""life""","""make""","""last""","""list""","""live""","""death""","""wrong""","""payback""","""shoot"""
1,"""film""","""suicide""","""life""","""escape""","""force""","""evidence""","""hold""","""master""","""star""","""political"""
2,"""life""","""mission""","""exist""","""record""","""set""","""daughter""","""help""","""man""","""film""","""green"""
3,"""put""","""send""","""get""","""force""","""back""","""unit""","""want""","""boot""","""cheat""","""kill"""
4,"""man""","""young""","""commit""","""start""","""death""","""involve""","""garbage""","""much""","""worker""","""nikander"""
...,...,...,...,...,...,...,...,...,...,...
5,"""red""","""car""","""book""","""film""","""girl""","""student""","""robe""","""silent""","""make""","""owner"""
6,"""use""","""day""","""horror""","""reflection""","""autumn""","""go""","""broadcasting""","""programme""","""material""","""extreme"""
7,"""foreign""","""national""","""citizen""","""civil""","""almost""","""yemeni""","""port""","""evacuation""","""war""","""loosely"""
8,"""find""","""heart""","""go""","""invasion""","""human""","""royalty""","""daughter""","""hollywood""","""follow""","""fight"""
9,"""interview""","""award""","""relation""","""win""","""rigid""","""issue""","""divisive""","""filmmaker""","""system""","""relate"""

      movie_id topic
0            2     4
1            3     4
2           12     7
3           13     8
4           14     2
...        ...   ...
11801   464610  3896
11802   464833  3896
11803   464888  3895
11805   464905  3894
11807   465079  3895

[11700 rows x 2 columns]