In [1]:
from utils import utils
from app import run_app, App

settings = utils.get_settings_notebook('../settings.json')
utils.pretty_print(settings)

=======
{
    "extract": {
        "cast": {
            "filepath_or_buffer": "files/archive/AllMoviesCastingRaw.csv",
            "sep": ";"
        },
        "directors": {
            "filepath_or_buffer": "files/archive/900_acclaimed_directors_awards.csv",
            "sep": ";"
        },
        "movies": {
            "filepath_or_buffer": "files/archive/AllMoviesDetailsCleaned.csv",
            "sep": ";"
        }
    },
    "load": {
        "constraints": [
            {
                "field": "name",
                "name": "Companies",
                "node_name": "Company"
            },
            {
                "field": "name",
                "name": "Genres",
                "node_name": "Genre"
            },
            {
                "field": "name",
                "name": "People",
                "node_name": "Person"
            },
            {
                "field": "movie_id",
                "name": "Movies",
                "node_name": "Movie"
            }
        ],
        "data": {
            "company": [
                {
                    "cols": [
                        "name"
                    ],
                    "node_name": "Company",
                    "ref": "c"
                }
            ],
            "genres": [
                {
                    "cols": [
                        "name"
                    ],
                    "node_name": "Genre",
                    "ref": "g"
                }
            ],
            "movies": [
                {
                    "cols": [
                        "movie_id",
                        "imdb_id",
                        "lang",
                        "title",
                        "overview"
                    ],
                    "node_name": "Movie",
                    "ref": "m"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Person",
                    "ref": "d",
                    "relations": [
                        {
                            "begins": "d",
                            "begins_dir": "-",
                            "ends": "m",
                            "ends_dir": "->",
                            "name": "DIRECTED"
                        }
                    ],
                    "unwind": "directors"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Company",
                    "ref": "c",
                    "relations": [
                        {
                            "begins": "c",
                            "begins_dir": "-",
                            "ends": "m",
                            "ends_dir": "->",
                            "name": "PRODUCED"
                        }
                    ],
                    "unwind": "companies"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Genre",
                    "ref": "g",
                    "relations": [
                        {
                            "begins": "m",
                            "begins_dir": "-",
                            "ends": "g",
                            "ends_dir": "->",
                            "name": "HAS_GENRE"
                        }
                    ],
                    "unwind": "genres"
                },
                {
                    "cols": [
                        "name"
                    ],
                    "needs": "m",
                    "node_name": "Person",
                    "ref": "a",
                    "relations": [
                        {
                            "begins": "a",
                            "begins_dir": "-",
                            "ends": "m",
                            "ends_dir": "->",
                            "name": "ACTED_IN"
                        }
                    ],
                    "unwind": "actors"
                }
            ],
            "people": [
                {
                    "cols": [
                        "name",
                        "gender"
                    ],
                    "node_name": "Person",
                    "ref": "p"
                }
            ]
        }
    },
    "neo4j": {
        "cap_insert": 25000,
        "clear_data": true,
        "db": null,
        "file_folder": "../import/",
        "insertion_mode": "rows",
        "password": "1234",
        "uri": "bolt://localhost:7687",
        "username": "neo4j"
    },
    "transform": {
        "cast": {
            "column_map": {
                "actor1_gender": "actor1_gender",
                "actor1_name": "actor1_name",
                "actor2_gender": "actor2_gender",
                "actor2_name": "actor2_name",
                "actor3_gender": "actor3_gender",
                "actor3_name": "actor3_name",
                "actor4_gender": "actor4_gender",
                "actor4_name": "actor4_name",
                "actor5_gender": "actor5_gender",
                "actor5_name": "actor5_name",
                "director_gender": "director_gender",
                "director_name": "director_name",
                "id": "movie_id"
            }
        },
        "directors": {
            "column_map": {
                "Academy Fellowship": "acad_fellow",
                "name": "name"
            }
        },
        "movies": {
            "column_map": {
                "genres": "genres",
                "id": "movie_id",
                "imdb_id": "imdb_id",
                "original_language": "lang",
                "original_title": "title",
                "overview": "overview",
                "production_companies": "company"
            }
        }
    }
}
======

In [2]:
data_df = run_app(settings, 'extract_transform')

==== TRANSFORM directors ====

/Users/leonardoclo/git/dse-203/src/core/core.py:8: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(**settings['extract'][k])

==== TRANSFORM movies ====
==== TRANSFORM cast ====

In [9]:
data_df['movies'].shape

(11444, 9)

In [7]:
import pandas as pd
# df = pd.read_csv(**settings['extract']['directors'])
# df = pd.read_csv(**settings['extract']['movies'])
# df = pd.read_csv(**settings['extract']['cast'])
df.head()

,name,tmdbID,imdbID,Total awards,Academy Fellowship,Academy Fellowship_won,Academy Fellowship_nominated,Gold Hugo,Gold Hugo_won,Gold Hugo_nominated,...,Orpheus Award_nominated,Arte France Cinéma Award,Arte France Cinéma Award_won,Arte France Cinéma Award_nominated,Citizens Award,Citizens Award_won,Citizens Award_nominated,Cowboy Award,Cowboy Award_won,Cowboy Award_nominated
0,Ingmar Bergman,6648,nm0000005,101,1,1,0,2,0,2,...,0,0,0,0,0,0,0,0,0,0
1,Marlon Brando,3084,nm0000008,58,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Federico Fellini,4415,nm0000019,90,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
3,Alfred Hitchcock,2636,nm0000033,53,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Buster Keaton,8635,nm0000036,5,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
def standardize(df, dir_col):
    df[dir_col] = df[dir_col].str.replace('[\W]+', ' ', regex=True) \
        .str.strip() \
        .str.title() \
        .astype("string") \
        .map(unidecode,na_action="ignore")

## CSV